# Generated by Django 5.2.3 on 2025-06-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingList', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppinglistitem',
            unique_together=set(),
        ),
    ]
