# Generated by Django 5.2.3 on 2025-06-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionproduct',
            unique_together=set(),
        ),
    ]
